### ISSUE TITLE
What income/wage variables should be used in drop-q?

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/drop-q#4]
Currently in dropq, we use this code to add a dollar to tax record income in order to figure out who are the taxpaying records:

```
    # add 1 dollar to gross income
    records2.e00200 += 1
    records2.e02000 += 1
    records2.e02615 += 1
```

We select from these records when choosing records to drop in the `dropq` algorithm. Recently, in Tax-Calculator, a [PR#826](https://github.com/open-source-economics/Tax-Calculator/pull/826/files) was merged that removed `e02615`. What is now the proper way to add one dollar to gross income to do this calculation?

Looking for input here @feenberg @martinholmer 

cc @MattHJensen

**Comment by martinholmer** [comment]
@talumbau, the `e02615` variable was removed because it was not read from the `puf.csv` file (and there is no mention of such a variable in the IRS-SOI 2009 PUF documentation) and it was not being used in Tax-Calculator.  The fact that it was being used in the drop-q repository and I didn't know that (because I've never worked on that part of the project) illustrates the need to move the drop-q code into the Tax-Calculator repository.  I raised this issue with @MattHJensen several weeks ago, but nothing has happened since then.  The issue you are raising would not come up if drop-q code was part of the Tax-Calculator.  Now that drop-q is public, is there any reason to keep that code separate?

Later this afternoon, I'll look at the code and make a suggestion about "What is now the proper way to add one dollar to gross income to do this calculation?"

@feenberg

**Comment by feenberg** [comment]
On Tue, 19 Jul 2016, T.J. Alumbaugh wrote:

> 
> Currently in dropq, we use this code to add a dollar to tax record income in order to
> figure out who are the taxpaying records:
>
>     # add 1 dollar to gross income
>     records2.e00200 += 1
>     records2.e02000 += 1
>     records2.e02615 += 1

Does e02000 affect income or is it calculated elsewhere and c02000 is 
actually used in calculating AGI? Same for e02615. If not this add $3 to 
gross income, $1 each to wages, Schedule E and Schedule H. I think it 
would make sense to only add to e00200 but I don't see anything in 
particular wrong with this approach. Any idea why it was adopted?

dan

**Comment by feenberg** [comment]
On Tue, 19 Jul 2016, Martin Holmer wrote:

> 
> Later this afternoon, I'll look at the code and make a suggestion about "What is now
> the proper way to add one dollar to gross income to do this calculation?"
>

I doubt that there is any way to add a dollar to gross income. You have to 
add it to a particular component of income. I think E00200 is the right 
choice, but it probably doesn't make much difference. That will raise 
gross income by a dollar except when the taxpayer is receiving social 
security benefits, in which case the increase may be 1.50 or 1.85. I don't 
think that matters for drop-q.

dan

**Comment by martinholmer** [comment]
@talumbau said:
> Currently in dropq, we use this code to add a dollar to tax record income in order to figure out who are the taxpaying records:
>
>```
    # add 1 dollar to gross income
    records2.e00200 += 1
    records2.e02000 += 1
    records2.e02615 += 1
```
> We select from these records when choosing records to drop in the dropq algorithm. Recently, in Tax-Calculator, a PR#826 was merged that removed e02615. What is now the proper way to add one dollar to gross income to do this calculation?

The code snippet above doesn't make any sense to me.  The lead comment says "add 1 dollar to gross income", but then one dollar is added to three different `e` variables.  What is the intent here?

Note that both `e00200` and `e02000` are part of AGI, which is the `c00100` in the code.

@MattHJensen @feenberg

**Comment by martinholmer** [comment]
Dan @feenberg said:
> I doubt that there is any way to add a dollar to gross income. You have to
add it to a particular component of income. I think E00200 is the right
choice, but it probably doesn't make much difference. That will raise
gross income by a dollar except when the taxpayer is receiving social
security benefits, in which case the increase may be 1.50 or 1.85. I don't
think that matters for drop-q.

I agree completely with Dan.  Why don't you revise the code to be something like this:
```
# add a small amount to adjusted gross income
records2.e00200 += 1.
```

@MattHJensen @feenberg @talumbau

**Comment by MattHJensen** [comment]
@Amy-Xu, could you take a look at @talumbau's question at the top of this thread and confirm whether @martinholmer's suggestion will resolve this issue?

**Comment by talumbau** [comment]
Thanks for the info all. I will go forward with a change like this:

```
# add a small amount to adjusted gross income
records2.e00200 += 1.
```

for now. I'll keep this issue open a bit longer to see if there is additional input.

**Comment by Amy-Xu** [comment]
Sorry this issue slipped through my hands. Yes, I think Martin's solution will work. Essentially we just want to add one dollar to AGI, and see how people with income tax liability change move between cells. Adding one dollar to wage and salaries should do the job well.
