### ISSUE TITLE
Need to review code after _fica changed to _payrolltax

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/drop-q#9]
[Tax-Calculator pull request #876](https://github.com/open-source-economics/Tax-Calculator/pull/876) changes `_fica` to `_payrolltax` throughout the source tree in the Tax-Calculator repository.  Because the dropq code has not yet been incorporated into the Tax-Calculator repository, someone with the ability to commit in the drop-q repository needs to review the source code to see if any changes need to be made in drop-q so that it can use the new version of the taxcalc package.

@MattHJensen @talumbau

**Comment by talumbau** [comment]
closed via #10
